name: Nuget Publish Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./packages
    - name: Publish Istanbul.ApiIdempotency
      run: dotnet nuget push ./packages/Istanbul.ApiIdempotency.1.0.0.nupkg --api-key ${{ secrets.NUGETKEY }}
     - name: Publish Istanbul.ApiIdempotency.Core
      run: dotnet nuget push ./packages/Istanbul.ApiIdempotency.Core.1.0.0.nupkg --api-key ${{ secrets.NUGETKEY }}
     - name: Publish Istanbul.ApiIdempotency.Redis.StackExchange
      run: dotnet nuget push ./packages/Istanbul.ApiIdempotency.Redis.StackExchange.1.0.0.nupkg --api-key ${{ secrets.NUGETKEY }}
