name: NugetPublishWorkflow

on:
  push:
    branches: [ main ]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore /p:Version=${VERSION}
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION} --no-restore
    - name: Test
      run: dotnet test /p:Version=${VERSION} --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --output ./packages
    - name: Publish packages
      run: dotnet nuget push "./packages/Istanbul.ApiIdempotency.*.nupkg" --api-key ${{ secrets.NUGETKEY }} --source https://api.nuget.org/v3/index.json
