name: NugetPublishWorkflow

on:
  push:
    branches: [ main ]
    tags:
      - '*.*.*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Show env
      run: echo $RELEASE_VERSION
    - name: Pack
      run: dotnet pack --configuration Release  --no-build --output ./packages
